# -*- coding: utf-8 -*-
"""AICP Week 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttmKOADQRzlJfk43IPs46mVT0y81mEs9
"""

#Question # 1

import matplotlib.pyplot as plt

x_values = [1.0, 1.5, 2.0, 2.5, 3.0]
y_values = [1.0, 2.0, 3.0, 3.5, 4.0]

plt.plot(x_values, y_values)

plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Line Plot Using Matplotlib')

plt.show()

#Question # 2

import matplotlib.pyplot as plt

x = [10, 20, 30, 40]
y1 = [20, 30, 35, 27]
y2 = [12, 43, 62, 18]

plt.plot(x, y1, label='Line 1', color='blue', linewidth=2)
plt.plot(x, y2, label='Line 2', color='red', linewidth=3)

plt.legend()

plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Multiple Lines Plot Using Matplotlib')

plt.show()

#Question # 3

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5, 6, 7, 8]
y1 = [1, 5, 4, 3, 2, 8, 5, 0]

plt.plot(x, y1, marker='o', label='Line 1')

plt.legend()

plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Multiple Lines with Markers Plot')

plt.show()

#Question # 4

import matplotlib.pyplot as plt

languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8, 7.7, 6.7]

plt.barh(languages, popularity, color='green')

plt.xlabel('Popularity')
plt.ylabel('Programming Languages')
plt.title('Popularity of Programming Languages')

plt.show()

#Question # 5

import pandas as pd
import matplotlib.pyplot as plt

data = {
    'a': [2, 4, 6, 8, 10],
    'b': [4, 2, 4, 2, 2],
    'c': [8, 3, 7, 6, 4],
    'd': [5, 4, 4, 4, 3],
    'e': [7, 2, 7, 8, 2]
}
df = pd.DataFrame(data)

df.plot(kind='bar')
plt.xlabel('Index')
plt.ylabel('Values')
plt.title('Bar Plot from DataFrame')
plt.show()

#Question # 6

#we shall use pandas along with matplotlib for this task

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/goldMedals.csv')

df = df.sort_values(by='Gold Medals', ascending=False)

top_countries = df.head(5)

plt.figure(figsize=(8, 6))
plt.pie(top_countries['Gold Medals'], labels=top_countries['Country'], autopct='%1.1f%%', startangle=140)
plt.title('Gold Medal Achievements of Five Most Successful Countries (2016 Summer Olympics)')
plt.axis('equal')
plt.show()

import matplotlib.pyplot as plt

math_marks = [88, 92, 80, 89, 100, 80, 60, 100, 80, 34]
science_marks = [35, 79, 79, 48, 100, 88, 32, 45, 20, 30]
marks_range = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

plt.scatter(math_marks, science_marks)

plt.xlabel('Mathematics Marks')
plt.ylabel('Science Marks')
plt.title('Scatter Plot Comparing Mathematics and Science Marks')

plt.show()

